name: Python Tests

on:
  push:
    paths:
      - '**.py'
      - 'tests/**'
      - '.github/workflows/python-tests.yml'
  pull_request:
    paths:
      - '**.py'
      - 'tests/**'
      - '.github/workflows/python-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
      - name: Install package
        run: pip install -e .
      - name: Run flake8
        run: flake8 api_gateway
      - name: Run tests
        run: pytest -q
